{
 "title": "Informations de la base de données",
 "tags": [ "tesla" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "length_unit",
    "label": "Unité de distance",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "Voiture",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "pg_stat_statements_info_last_reset",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'SELECT stats_reset FROM pg_stat_statements_info;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_count",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'SELECT count(*) FROM pg_stat_statements;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_top_20_mean",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'select\n  calls as \"Calls\",\n  mean_exec_time as \"Mean Exec Time\",\n  total_exec_time as \"Total Exec Time\",\n  query as \"Query\"\nfrom pg_stat_statements\nORDER BY mean_exec_time desc\nlimit 20;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_top_20_total",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'select\n  calls as \"Calls\",\n  mean_exec_time as \"Mean Exec Time\",\n  total_exec_time as \"Total Exec Time\",\n  query as \"Query\"\nfrom pg_stat_statements\nORDER BY total_exec_time desc\nlimit 20;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_enabled",
    "query": "SELECT EXISTS (\nSELECT 1\nFROM information_schema.tables\nWHERE table_name = 'pg_stat_statements'\n)::int AS table_existence"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Kilométrage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(convert_km(sum(distance)::numeric, '$length_unit'), 0) || ' $length_unit' as \"Logged\",\n  ROUND(convert_km(max(end_km)::numeric, '$length_unit'), 0) || ' $length_unit' as \"Odometer\"\nfrom drives where car_id = $car_id;"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"Charges\" FROM charging_processes WHERE car_id=$car_id \n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"Drives\" FROM drives WHERE car_id=$car_id "
    }
   ]
  },
  {
   "title": "Logiciel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Nº Car Updates\"\nFROM Updates \nWHERE car_id = $car_id\n"
    },
    {
     "rawSql": "select split_part(version, ' ', 1) as \"Current Car Firmware\" \r\nfrom updates \r\nwhere car_id = $car_id \r\norder by start_date desc \r\nlimit 1"
    }
   ]
  },
  {
   "title": "Données incomplètes",
   "type": "stat",
   "description": "Cela signifie que vous avez des **Trajets** ou des **Charges** non clôturés.\nSi c'est le cas, vous pouvez suivre le guide officiel : \n<a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data' target='_blank'>Correction manuelle des données</a>",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Charges not closed\"\nFROM charging_processes \nWHERE car_id = $car_id AND end_date is null\n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"Drives not closed\"\r\nFROM drives \r\nWHERE car_id = $car_id AND end_date is null"
    }
   ]
  },
  {
   "title": "Version PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT regexp_replace(version(), 'PostgreSQL ([^ ]+) .*', '\\1') AS version;"
    }
   ]
  },
  {
   "title": "Informations de la base de données",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n   relname AS \"Table\",\r\n   pg_relation_size(relid) as \"Data\",\r\n   pg_indexes_size(relid) as \"Indexes\",\r\n   pg_total_relation_size(relid) As \"Total\"\r\nFROM \r\n   pg_catalog.pg_statio_user_tables\r\nORDER BY \r\n   pg_total_relation_size(relid) DESC;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS \"Table Name\", \r\n       (xpath('/row/cnt/text()', xml_count))[1]::text::int AS \"Row Count\"\r\nFROM (\r\n    SELECT table_name, \r\n           query_to_xml(format('SELECT count(*) as cnt FROM %I.%I', table_schema, table_name), false, true, '') AS xml_count\r\n    FROM information_schema.tables\r\n    WHERE table_schema NOT IN ('pg_catalog', 'information_schema') and table_type = 'BASE TABLE'\r\n) AS t\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Index",
   "type": "table",
   "description": "Ces statistiques peuvent vous aider à évaluer l'efficacité de vos index.\n\nSi votre base de données subit de nombreuses mises à jour ou suppressions, comme l'import de données d'autres sources ou la suppression d'une voiture de prêt, vous pouvez rencontrer un gonflement des index, ce qui peut dégrader les performances. Dans ce cas, une réindexation peut être bénéfique.\n\nVoir <a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data#reindex-database' target='_blank'>Réindexer la base</a>",
   "gridPos": { "h": 19, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    relname AS \"Table\",\r\n    indexrelname AS \"Index\",\r\n    idx_scan AS \"Index Scans\",\r\n    idx_tup_read AS \"Tuples Read\",\r\n    idx_tup_fetch AS \"Tuples Fetched\",\r\n    PG_RELATION_SIZE(indexrelid) as \"Index Size\"\r\nFROM\r\n    pg_stat_all_indexes\r\nWHERE\r\n    schemaname NOT LIKE 'pg_%' AND\r\n    indexrelname IS NOT NULL\r\nORDER BY 3 DESC;"
    }
   ]
  },
  {
   "title": "Taille totale de la base de données",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(pg_total_relation_size(relid)) As \"Size\"\nFROM \n    pg_catalog.pg_statio_user_tables;"
    }
   ]
  },
  {
   "title": "Buffers partagés",
   "type": "stat",
   "description": "<b>Shared Buffers :</b> Cette métrique montre la quantité de mémoire que PostgreSQL utilise pour stocker les données fréquemment consultées, comme les tables et index, afin d'accélérer les requêtes en évitant les lectures disque lentes.\n\n<b>Valeur recommandée :</b> Utilisez environ 25 % de la RAM totale de votre système (par ex. 1GB pour un système avec 4GB de RAM). Commencez avec une valeur modeste et ajustez selon les besoins de votre application. La fixer trop haut peut gaspiller de la mémoire.\n\n<b>Pour modifier dans un fichier Docker Compose Postgres :</b> Dans votre docker-compose.yml, ajoutez ou mettez à jour le champ command du service Postgres pour inclure le paramètre shared_buffers. Par exemple :\n\n<pre>\nservices:\n  database:\n    image: postgres:18-trixie\n    command: postgres -c shared_buffers=1GB\n    ...\n</pre>\n\nAprès avoir mis à jour le fichier, exécutez <code>docker compose down</code> et <code>docker compose up -d</code> pour redémarrer le conteneur et appliquer le changement.\n\nPour plus de détails : <a href='https://www.postgresql.org/docs/18/runtime-config-resource.html#GUC-SHARED-BUFFERS' target='_blank'>PostgreSQL : Documentation : 18 : 19.4. Consommation des ressources</a>",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(setting as numeric) * 8 * 1024 FROM pg_catalog.pg_settings WHERE name = 'shared_buffers';"
    }
   ]
  },
  {
   "title": "Fuseau horaire",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "show timezone;" }
   ]
  },
  {
   "title": "Statistiques de planification et d'exécution SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Moment où toutes les statistiques de la vue pg_stat_statements ont été réinitialisées",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_info_last_reset:raw}"
    }
   ]
  },
  {
   "title": "Nombre de requêtes suivies via pg_stat_statements",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_count:raw}"
    }
   ]
  },
  {
   "title": "À propos de pg_stat_statements (suivi des statistiques de planification et d'exécution SQL)",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "options": {
    "content": "Consultez les [docs de contribution](https://docs.teslamate.org/docs/development#enable-pg_stat_statements-to-collect-query-statistics) pour activer le suivi des statistiques de planification et d'exécution de toutes les requêtes SQL exécutées par un serveur.\n"
   }
  },
  {
   "title": "Top 20 requêtes (par temps moyen d'exécution)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_top_20_mean:raw}"
    }
   ]
  },
  {
   "title": "Top 20 requêtes (par temps total d'exécution)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_top_20_total:raw}"
    }
   ]
  }
 ]
}